version: '3'
services:
  lb:
    build: .
    # volumes:
    #   - ./web1/web:/usr/share/nginx/web-app
    ports:
      - '8080:80'

  web:
    build: ./web1
    volumes:
      - ./web1/web:/usr/share/nginx/web-app
    ports:
      - '8082:80'

  web2:
    build: ./web2
    volumes:
      - ./web2/web:/usr/share/nginx/web-app
    ports:
      - '8081:80'

  nodeapp:
    build:
      context: ./nodeapp1
    ports:
      - '3000:3000'

  nodeapp2:
    build:
      context: ./nodeapp2
    ports:
      - '3001:3000'

  nodeapp3:
    build:
      context: ./nodeapp3
    ports:
      - '3002:3000'
